# Generated by Django 2.2.3 on 2019-08-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('hyperlink', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('owned_by', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
